- name: type:feature
  color: "1f883d"
  description: Feature/enhancement
- name: type:bug
  color: "d73a4a"
  description: Bug report
- name: type:docs
  color: "0e8a16"
  description: Documentation
