name: Bug report
description: Report something broken
labels: ["type:bug"]
body:
  - type: input
    id: version
    attributes: { label: Version / commit }
  - type: textarea
    id: repro
    attributes: { label: Repro steps }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs / screenshots }
