blank_issues_enabled: false
contact_links:
  - name: Security / vulnerability report
    url: https://github.com/aurelianware/ai-security-monitoring-app/security/advisories/new
    about: Report a security issue privately.
