name: Feature request
description: Propose an enhancement
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem, description: What problem does this solve? }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposal, description: What should change? }
    validations: { required: true }
  - type: textarea
    id: notes
    attributes: { label: Notes, description: Additional context or alternatives }
