name: Deploy to Azure App Service (DISABLED)

# DISABLED: Using container deployment instead (azure-deploy-container.yml)
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'This workflow is disabled'
        required: false
        default: 'Use azure-deploy-container.yml instead'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Disabled
      run: |
        echo "This workflow is disabled. Use azure-deploy-container.yml instead."
        exit 1